"""Add dual language columns for auto translation

Revision ID: 1168a000014e
Revises: fad0b609eb1c
Create Date: 2026-09-06 11:50:45.718713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1168a000014e'
down_revision = 'fad0b609eb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('admin_notes_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('admin_notes_en', sa.Text(), nullable=True))
        batch_op.drop_column('notes')
        batch_op.drop_column('admin_notes')

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requirements_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requirements_en', sa.Text(), nullable=True))
        batch_op.drop_column('title')
        batch_op.drop_column('requirements')
        batch_op.drop_column('description')

    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('content_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_en', sa.Text(), nullable=True))
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))
        batch_op.drop_column('title')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('description_en')
        batch_op.drop_column('description_es')
        batch_op.drop_column('title_en')
        batch_op.drop_column('title_es')

    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('content_en')
        batch_op.drop_column('content_es')
        batch_op.drop_column('title_en')
        batch_op.drop_column('title_es')

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('requirements_en')
        batch_op.drop_column('requirements_es')
        batch_op.drop_column('description_en')
        batch_op.drop_column('description_es')
        batch_op.drop_column('title_en')
        batch_op.drop_column('title_es')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('admin_notes_en')
        batch_op.drop_column('admin_notes_es')
        batch_op.drop_column('notes_en')
        batch_op.drop_column('notes_es')

    # ### end Alembic commands ###
