"""Fix model columns for dual language properties

Revision ID: 571bc9c81134
Revises: ee490e523ead
Create Date: 2026-09-06 10:37:46.005369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571bc9c81134'
down_revision = 'ee490e523ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requirements_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requirements_en', sa.Text(), nullable=True))

    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('content_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_en', sa.Text(), nullable=True))

    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.drop_column('description_en')
        batch_op.drop_column('description_es')
        batch_op.drop_column('title_en')
        batch_op.drop_column('title_es')

    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.drop_column('content_en')
        batch_op.drop_column('content_es')
        batch_op.drop_column('title_en')
        batch_op.drop_column('title_es')

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_column('requirements_en')
        batch_op.drop_column('requirements_es')
        batch_op.drop_column('description_en')
        batch_op.drop_column('description_es')
        batch_op.drop_column('title_en')
        batch_op.drop_column('title_es')

    # ### end Alembic commands ###
