"""Fix model columns for dual language properties

Revision ID: 7148be7b0a10
Revises: 1168a000014e
Create Date: 2026-09-06 12:31:19.300668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7148be7b0a10'
down_revision = '1168a000014e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes_', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))
        batch_op.drop_column('notes_en')
        batch_op.drop_column('notes_es')
        batch_op.drop_column('admin_notes_es')
        batch_op.drop_column('admin_notes_en')

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))
        batch_op.drop_column('description_es')
        batch_op.drop_column('title_en')
        batch_op.drop_column('description_en')
        batch_op.drop_column('requirements_es')
        batch_op.drop_column('title_es')
        batch_op.drop_column('requirements_en')

    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.drop_column('content_en')
        batch_op.drop_column('title_en')
        batch_op.drop_column('content_es')
        batch_op.drop_column('title_es')

    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('title_en')
        batch_op.drop_column('description_en')
        batch_op.drop_column('title_es')
        batch_op.drop_column('description_es')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_es', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title_es', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content_es', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content_en', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements_en', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title_es', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requirements_es', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description_es', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('requirements')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notes_en', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('admin_notes_es', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes_es', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes_en', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('notes_')

    # ### end Alembic commands ###
