"""add missing news_post columns

Revision ID: edf68f2ee452
Revises: 
Create Date: 2026-09-18 15:42:54.186402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf68f2ee452'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes_', sa.Text(), nullable=True))
        batch_op.drop_column('notes')

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))

    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_column('requirements')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('notes_')

    # ### end Alembic commands ###
