"""Add property_listing and dual language fields

Revision ID: ee490e523ead
Revises: e93212df0271
Create Date: 2026-09-05 16:33:43.456039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee490e523ead'
down_revision = 'e93212df0271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_type', sa.String(length=50), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_period', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('case_case_id_fkey'), type_='foreignkey')
        batch_op.drop_column('case_id')

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_column('requirements')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('case_case_id_fkey'), 'case', ['case_id'], ['id'])

    op.drop_table('property_listing')
    # ### end Alembic commands ###
