"""Fix model columns for dual language properties

Revision ID: fad0b609eb1c
Revises: 571bc9c81134
Create Date: 2026-09-06 11:34:26.723133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad0b609eb1c'
down_revision = '571bc9c81134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))
        batch_op.drop_column('description_es')
        batch_op.drop_column('description_en')
        batch_op.drop_column('requirements_en')
        batch_op.drop_column('title_es')
        batch_op.drop_column('requirements_es')
        batch_op.drop_column('title_en')

    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('title_en')
        batch_op.drop_column('title_es')
        batch_op.drop_column('content_en')
        batch_op.drop_column('content_es')

    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.drop_column('title_en')
        batch_op.drop_column('title_es')
        batch_op.drop_column('description_es')
        batch_op.drop_column('description_en')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description_es', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title_es', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_es', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content_en', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title_es', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requirements_es', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title_es', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requirements_en', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description_es', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('requirements')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
